# Generated by Django 5.0.6 on 2024-07-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
        ('library', '0004_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=255, verbose_name='Номер поставки')),
                ('delivery_data', models.DateField(verbose_name='Дата поставки')),
                ('delivery_price', models.FloatField(verbose_name='Цена')),
                ('delivery_count', models.FloatField(default=1, verbose_name='Количество поставок')),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.book')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.provider')),
            ],
        ),
    ]
